/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: ../sanity.schema.json
export type HeadingMultipart = {
  faded?: string
  regular?: string
  bold?: string
  trailing?: string
}

export type FormConfig = {
  services?: Array<string>
  budgetRanges?: Array<string>
  timelines?: Array<string>
  hearAboutUs?: Array<string>
}

export type ContactFormFormConfig = {
  services?: Array<string>
  budgetRanges?: Array<string>
  timelines?: Array<string>
  hearAboutUs?: Array<string>
}

export type Callout = {
  heading?: string
  body?: string
  cta?: Button
}

export type ValueCard = {
  value?: string
  body?: string
}

export type SanityImageAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type Logo = {
  asset?: SanityImageAssetReference
  media?: unknown // Unable to locate the referenced type "media" in schema
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  _type: 'image'
}

export type Texture = {
  asset?: SanityImageAssetReference
  media?: unknown // Unable to locate the referenced type "texture.media" in schema
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  _type: 'image'
}

export type Industries = {
  _type: 'industries'
  eyebrow?: string
  heading?: string
  industries?: Array<{
    industry?: string
    description?: string
    _key: string
  }>
  metrics?: Array<{
    label?: string
    value?: string
    prefix?: string
    _key: string
  }>
}

export type ServiceReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'service'
}

export type AiServices = {
  _type: 'aiServices'
  eyebrow?: string
  services?: Array<{
    service?: ServiceReference
    cta: Button
    _key: string
  }>
}

export type Button = {
  _type: 'button'
  buttonText?: string
  link?: Link
}

export type EngineeringServices = {
  _type: 'engineeringServices'
  eyebrow?: string
  services?: Array<{
    service?: ServiceReference
    ctaLabel?: string
    ctaHref?: string
    _key: string
  }>
}

export type Faq = {
  _type: 'faq'
  eyebrow?: string
  heading?: string
  items: Array<{
    question: string
    answer: Array<{
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        href?: string
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }>
    _key: string
  }>
}

export type Why = {
  _type: 'why'
  eyebrow?: string
  heading?: string
  points?: Array<{
    title?: string
    body?: string
    _key: string
  }>
}

export type WhatWeDo = {
  _type: 'whatWeDo'
  eyebrow?: string
  cards: Array<{
    kind?: 'engineering' | 'ai'
    label?: string
    title: string
    body: string
    services?: Array<
      {
        _key: string
      } & ServiceReference
    >
    cta: Button
    texture?: Texture
    _key: string
  }>
}

export type TestimonialReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'testimonial'
}

export type Testimonials = {
  _type: 'testimonials'
  eyebrow: string
  logos: Array<{
    name: string
    logo: Logo
    _key: string
  }>
  testimonials: Array<
    {
      _key: string
    } & TestimonialReference
  >
}

export type TeamMemberReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'teamMember'
}

export type Team = {
  _type: 'team'
  eyebrow?: string
  heading: string
  members: Array<
    {
      _key: string
    } & TeamMemberReference
  >
  closingStatement: string
}

export type Story = {
  _type: 'story'
  eyebrow?: string
  heading?: string
  milestones?: Array<{
    year?: string
    body?: string
    _key: string
  }>
}

export type Signature = {
  _type: 'signature'
  eyebrow?: string
  heading?: string
  body?: string
  secondaryLine?: string
  steps?: Array<{
    title?: string
    duration?: string
    body?: string
    textured?: boolean
    _key: string
  }>
  cta?: Button
  valueCard?: ValueCard
}

export type Pricing = {
  _type: 'pricing'
  eyebrow?: string
  heading?: string
  cards?: Array<{
    kind?: 'engineering' | 'ai'
    title?: string
    items?: Array<
      {
        _key: string
      } & ServiceReference
    >
    _key: string
  }>
  callout?: Callout
}

export type ProjectReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'project'
}

export type Portfolio = {
  _type: 'portfolio'
  eyebrow: string
  heading: string
  projects: Array<
    {
      _key: string
    } & ProjectReference
  >
}

export type Origin = {
  _type: 'origin'
  eyebrow?: string
  heading: string
  body: string
  subtext?: string
}

export type Methodology = {
  _type: 'methodology'
  eyebrow?: string
  heading?: string
  steps?: Array<{
    title?: string
    body?: string
    _key: string
  }>
}

export type Cta = {
  _type: 'cta'
  heading: string
  body: string
  cta: Button
  subtext?: string
}

export type HomeHero = {
  _type: 'homeHero'
  label?: string
  heading?: string
  body?: string
  primaryCta?: Button
  stats?: string
  dimensionLine?: string
  ctaText: string
  secondaryCta?: Button
}

export type ContactForm = {
  _type: 'contactForm'
  eyebrow?: string
  heading: string
  description: string
  steps: Array<{
    title: string
    description: string
    _key: string
  }>
  formConfig?: ContactFormFormConfig
}

export type ContactHero = {
  _type: 'contactHero'
  eyebrow?: string
  heading: string
  description: string
  steps: Array<{
    title: string
    description: string
    _key: string
  }>
  formConfig?: FormConfig
}

export type PageHero = {
  _type: 'pageHero'
  eyebrow?: string
  headingType: 'simple' | 'multipart'
  heading?: string
  headingMultipart?: HeadingMultipart
  subheading?: string
  stats?: Array<{
    number: number
    suffix?: string
    label: string
    _key: string
  }>
}

export type List = {
  _type: 'list'
  pageBuilder?: null
}

export type PageReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'page'
}

export type PostReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'post'
}

export type Link = {
  _type: 'link'
  linkType?: 'href' | 'page' | 'post'
  href?: string
  page?: PageReference
  post?: PostReference
  openInNewTab?: boolean
}

export type BlockContentTextOnly = Array<{
  children?: Array<{
    marks?: Array<string>
    text?: string
    _type: 'span'
    _key: string
  }>
  style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
  listItem?: 'bullet' | 'number'
  markDefs?: Array<{
    href?: string
    _type: 'link'
    _key: string
  }>
  level?: number
  _type: 'block'
  _key: string
}>

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        linkType?: 'href' | 'page' | 'post'
        href?: string
        page?: PageReference
        post?: PostReference
        openInNewTab?: boolean
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }
  | {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
      _key: string
    }
>

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top: number
  bottom: number
  left: number
  right: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x: number
  y: number
  height: number
  width: number
}

export type Testimonial = {
  _id: string
  _type: 'testimonial'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  attribution: string
  quote: string
  profilePicture?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
}

export type Project = {
  _id: string
  _type: 'project'
  _createdAt: string
  _updatedAt: string
  _rev: string
  client: string
  year: string
  slug: Slug
  category: 'engineering' | 'ai'
  title: string
  tagline: string
  description: string
  image: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  link: string
}

export type Slug = {
  _type: 'slug'
  current: string
  source?: string
}

export type Person = {
  _id: string
  _type: 'person'
  _createdAt: string
  _updatedAt: string
  _rev: string
  firstName: string
  lastName: string
  picture: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
}

export type PrivacyPolicy = {
  _id: string
  _type: 'privacyPolicy'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
}

export type TermsAndConditions = {
  _id: string
  _type: 'termsAndConditions'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
}

export type SiteSettings = {
  _id: string
  _type: 'siteSettings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  description?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: Array<{
      linkType?: 'href' | 'page' | 'post'
      href?: string
      page?: PageReference
      post?: PostReference
      openInNewTab?: boolean
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  ogImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    metadataBase?: string
    _type: 'image'
  }
  brandName: string
  logoPicture?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  legalName?: string
  email?: string
  phoneNumber?: string
  location?: string
  instagram?: string
  facebook?: string
  linkedin?: string
  github?: string
  x?: string
  tiktok?: string
  cta?: Button
  navLinks?: Array<{
    label: string
    page?: PageReference
    href?: string
    _key: string
  }>
  footerColumns?: Array<{
    title: string
    links?: Array<{
      label: string
      linkType: 'page' | 'service' | 'href'
      page?: PageReference
      service?: ServiceReference
      href?: string
      accent?: boolean
      _key: string
    }>
    _key: string
  }>
}

export type Post = {
  _id: string
  _type: 'post'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
  publishedAt?: string
  excerpt?: string
  cover?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  author?: TeamMemberReference
  category?:
    | 'ai-transformation'
    | 'engineering'
    | 'design-research'
    | 'systems-playbooks'
    | 'operators-notes'
  readTime?: number
  featured?: boolean
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'normal' | 'h2' | 'h3' | 'blockquote'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<{
          href?: string
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: SanityImageAssetReference
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        _type: 'image'
        _key: string
      }
    | {
        quote?: string
        attribution?: string
        _type: 'pullquote'
        _key: string
      }
    | {
        label?: string
        body?: string
        _type: 'keyPoint'
        _key: string
      }
    | {
        headers?: Array<string>
        rows?: Array<{
          cells?: Array<string>
          _key: string
        }>
        _type: 'comparisonTable'
        _key: string
      }
  >
  relatedInsights?: Array<
    {
      _key: string
    } & PostReference
  >
  order?: number
}

export type TeamMember = {
  _id: string
  _type: 'teamMember'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  order: number
  role: string
  bio: string
  portrait?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
}

export type Page = {
  _id: string
  _type: 'page'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  slug: Slug
  pageType?: 'home' | 'services' | 'insights' | 'caseStudies'
  description: string
  keywords: Array<string>
  pageBuilder?: Array<
    | ({
        _key: string
      } & PageHero)
    | ({
        _key: string
      } & ContactHero)
    | ({
        _key: string
      } & ContactForm)
    | ({
        _key: string
      } & HomeHero)
    | ({
        _key: string
      } & List)
    | ({
        _key: string
      } & Cta)
    | ({
        _key: string
      } & Methodology)
    | ({
        _key: string
      } & Origin)
    | ({
        _key: string
      } & Portfolio)
    | ({
        _key: string
      } & Pricing)
    | ({
        _key: string
      } & Signature)
    | ({
        _key: string
      } & Story)
    | ({
        _key: string
      } & Team)
    | ({
        _key: string
      } & Testimonials)
    | ({
        _key: string
      } & WhatWeDo)
    | ({
        _key: string
      } & Why)
    | ({
        _key: string
      } & EngineeringServices)
    | ({
        _key: string
      } & Industries)
    | ({
        _key: string
      } & Faq)
  >
}

export type Service = {
  _id: string
  _type: 'service'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  price: string
  category: 'engineering' | 'ai'
  tag: string
  slug: Slug
  description: string
  keywords: Array<string>
  duration: string
  pageBuilder?: Array<
    | ({
        _key: string
      } & PageHero)
    | ({
        _key: string
      } & ContactHero)
    | ({
        _key: string
      } & ContactForm)
    | ({
        _key: string
      } & HomeHero)
    | ({
        _key: string
      } & List)
    | ({
        _key: string
      } & Cta)
    | ({
        _key: string
      } & Methodology)
    | ({
        _key: string
      } & Origin)
    | ({
        _key: string
      } & Portfolio)
    | ({
        _key: string
      } & Pricing)
    | ({
        _key: string
      } & Signature)
    | ({
        _key: string
      } & Story)
    | ({
        _key: string
      } & Team)
    | ({
        _key: string
      } & Testimonials)
    | ({
        _key: string
      } & WhatWeDo)
    | ({
        _key: string
      } & Why)
    | ({
        _key: string
      } & EngineeringServices)
    | ({
        _key: string
      } & Faq)
  >
}

export type SanityAssistInstructionTask = {
  _type: 'sanity.assist.instructionTask'
  path?: string
  instructionKey?: string
  started?: string
  updated?: string
  info?: string
}

export type SanityAssistTaskStatus = {
  _type: 'sanity.assist.task.status'
  tasks?: Array<
    {
      _key: string
    } & SanityAssistInstructionTask
  >
}

export type SanityAssistSchemaTypeAnnotations = {
  _type: 'sanity.assist.schemaType.annotations'
  title?: string
  fields?: Array<
    {
      _key: string
    } & SanityAssistSchemaTypeField
  >
}

export type SanityAssistOutputType = {
  _type: 'sanity.assist.output.type'
  type?: string
}

export type SanityAssistOutputField = {
  _type: 'sanity.assist.output.field'
  path?: string
}

export type AssistInstructionContextReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'assist.instruction.context'
}

export type SanityAssistInstructionContext = {
  _type: 'sanity.assist.instruction.context'
  reference: AssistInstructionContextReference
}

export type AssistInstructionContext = {
  _id: string
  _type: 'assist.instruction.context'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  context?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: null
    level?: number
    _type: 'block'
    _key: string
  }>
}

export type SanityAssistInstructionUserInput = {
  _type: 'sanity.assist.instruction.userInput'
  message: string
  description?: string
}

export type SanityAssistInstructionPrompt = Array<{
  children?: Array<
    | {
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }
    | ({
        _key: string
      } & SanityAssistInstructionFieldRef)
    | ({
        _key: string
      } & SanityAssistInstructionContext)
    | ({
        _key: string
      } & SanityAssistInstructionUserInput)
  >
  style?: 'normal'
  listItem?: never
  markDefs?: null
  level?: number
  _type: 'block'
  _key: string
}>

export type SanityAssistInstructionFieldRef = {
  _type: 'sanity.assist.instruction.fieldRef'
  path?: string
}

export type SanityAssistInstruction = {
  _type: 'sanity.assist.instruction'
  prompt?: SanityAssistInstructionPrompt
  icon?: string
  title?: string
  userId?: string
  createdById?: string
  output?: Array<
    | ({
        _key: string
      } & SanityAssistOutputField)
    | ({
        _key: string
      } & SanityAssistOutputType)
  >
}

export type SanityAssistSchemaTypeField = {
  _type: 'sanity.assist.schemaType.field'
  path?: string
  instructions?: Array<
    {
      _key: string
    } & SanityAssistInstruction
  >
}

export type MediaTag = {
  _id: string
  _type: 'media.tag'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: Slug
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height: number
  width: number
  aspectRatio: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | HeadingMultipart
  | FormConfig
  | ContactFormFormConfig
  | Callout
  | ValueCard
  | SanityImageAssetReference
  | Logo
  | Texture
  | Industries
  | ServiceReference
  | AiServices
  | Button
  | EngineeringServices
  | Faq
  | Why
  | WhatWeDo
  | TestimonialReference
  | Testimonials
  | TeamMemberReference
  | Team
  | Story
  | Signature
  | Pricing
  | ProjectReference
  | Portfolio
  | Origin
  | Methodology
  | Cta
  | HomeHero
  | ContactForm
  | ContactHero
  | PageHero
  | List
  | PageReference
  | PostReference
  | Link
  | BlockContentTextOnly
  | BlockContent
  | SanityImageCrop
  | SanityImageHotspot
  | Testimonial
  | Project
  | Slug
  | Person
  | PrivacyPolicy
  | TermsAndConditions
  | SiteSettings
  | Post
  | TeamMember
  | Page
  | Service
  | SanityAssistInstructionTask
  | SanityAssistTaskStatus
  | SanityAssistSchemaTypeAnnotations
  | SanityAssistOutputType
  | SanityAssistOutputField
  | AssistInstructionContextReference
  | SanityAssistInstructionContext
  | AssistInstructionContext
  | SanityAssistInstructionUserInput
  | SanityAssistInstructionPrompt
  | SanityAssistInstructionFieldRef
  | SanityAssistInstruction
  | SanityAssistSchemaTypeField
  | MediaTag
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
