/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: ../sanity.schema.json
export type FormConfig = {
  services?: Array<string>
  budgetRanges?: Array<string>
  timelines?: Array<string>
  hearAboutUs?: Array<string>
}

export type Heading = {
  regular?: string
  bold?: string
}

export type ValueCard = {
  value?: string
  body?: string
  graphic?: Graphic
}

export type CtaSection = {
  heading?: string
  subheading?: string
  cta?: Button
}

export type Breadcrumb = {
  rootLabel?: string
  categoryLabel?: string
  currentLabel?: string
}

export type RealityHeading = {
  faded?: string
  bold: string
}

export type CompareHeading = {
  highlighted: string
  regular: string
}

export type Closing = {
  lead: string
  highlight: string
  followup: string
}

export type PortfolioCtaHeading = {
  regular: string
  bold: string
}

export type FreeResourcesHeading = {
  faded?: string
  bold?: string
  regular?: string
  trailing?: string
}

export type Quote = {
  quote?: BlockContentTextOnly
  attribution?: string
}

export type Table = {
  headers?: Array<string>
  rows?: Array<{
    cells?: Array<string>
    _key: string
  }>
}

export type Card = {
  label?: string
  body?: BlockContentTextOnly
}

export type StudyApproachHeading = {
  faded?: string
  bold: string
}

export type Callout = {
  label?: string
  body?: string
}

export type Comparison = {
  beforeLabel?: string
  afterLabel?: string
  rows: Array<{
    label: string
    before: string
    after: string
    _key: string
  }>
}

export type StudyTestimonialQuote = {
  quote: string
  attribution: string
  source?: string
  accent?: boolean
}

export type StudyMoreLikeThisHeading = {
  regular?: string
  bold?: string
}

export type StudyClosingCtaHeading = {
  regular: string
  bold: string
}

export type SanityImageAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type Graphic = {
  asset?: SanityImageAssetReference
  media?: unknown // Unable to locate the referenced type "graphic.media" in schema
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  _type: 'image'
}

export type StepGraphic = {
  asset?: SanityImageAssetReference
  media?: unknown // Unable to locate the referenced type "step.graphic.media" in schema
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  _type: 'image'
}

export type LogoLight = {
  asset?: SanityImageAssetReference
  media?: unknown // Unable to locate the referenced type "logoLight.media" in schema
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  _type: 'image'
}

export type LogoDark = {
  asset?: SanityImageAssetReference
  media?: unknown // Unable to locate the referenced type "logoDark.media" in schema
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  _type: 'image'
}

export type LabelImage = {
  asset?: SanityImageAssetReference
  media?: unknown // Unable to locate the referenced type "labelImage.media" in schema
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  _type: 'image'
}

export type LabelImageLight = {
  asset?: SanityImageAssetReference
  media?: unknown // Unable to locate the referenced type "labelImageLight.media" in schema
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  _type: 'image'
}

export type LabelImageDark = {
  asset?: SanityImageAssetReference
  media?: unknown // Unable to locate the referenced type "labelImageDark.media" in schema
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  _type: 'image'
}

export type Logo = {
  asset?: SanityImageAssetReference
  media?: unknown // Unable to locate the referenced type "logo.media" in schema
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  _type: 'image'
}

export type SanityFileAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.fileAsset'
}

export type ResourceFile = {
  asset?: SanityFileAssetReference
  media?: unknown // Unable to locate the referenced type "resource.file.media" in schema
  _type: 'file'
}

export type ObjectImage = {
  asset?: SanityImageAssetReference
  media?: unknown // Unable to locate the referenced type "object.image.media" in schema
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  _type: 'image'
}

export type Steps = {
  _type: 'steps'
  eyebrow?: string
  intro: string
  highlight: string
  items: Array<{
    title: string
    duration?: string
    body: string
    _key: string
  }>
  visual?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  visualAlt?: string
}

export type ServiceNavigator = {
  _type: 'serviceNavigator'
  eyebrow?: string
  headingRegular: string
  headingBold: string
  cards: Array<{
    prompt: string
    details?: string
    cta: Button
    _key: string
  }>
  closingText?: string
  closingCta: Button
}

export type SoundFamiliar = {
  _type: 'soundFamiliar'
  eyebrow?: string
  heading?: string
  painPoints?: Array<{
    title: string
    body?: string
    _key: string
  }>
}

export type IsThisForYou = {
  _type: 'isThisForYou'
  eyebrow?: string
  heading: string
  items: Array<{
    text: string
    _key: string
  }>
}

export type FreeResources = {
  _type: 'freeResources'
  eyebrow?: string
  heading?: FreeResourcesHeading
  body?: string
  footnote?: string
  items?: Array<{
    title: string
    badge?: string
    description?: string
    file?: ResourceFile
    externalUrl?: string
    emailIt?: boolean
    _type: 'resource'
    _key: string
  }>
}

export type StudyClosingCta = {
  _type: 'studyClosingCta'
  heading?: StudyClosingCtaHeading
  body?: string
  cta?: Button
}

export type TechStack = {
  _type: 'techStack'
  eyebrow?: string
  headingRegular?: string
  headingBold: string
  groups?: Array<{
    title: string
    items?: Array<{
      name: string
      logo?: Logo
      _type: 'item'
      _key: string
    }>
    _type: 'group'
    _key: string
  }>
  closingNote?: string
}

export type Press = {
  _type: 'press'
  eyebrow?: string
  heading: string
  cardTitle: string
  cardBody: string
  ctaLabel: string
  file: {
    asset?: SanityFileAssetReference
    media?: unknown
    _type: 'file'
  }
}

export type Place = {
  _type: 'place'
  message?: string
  backgroundGraphic?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
}

export type Awards = {
  _type: 'awards'
  eyebrow?: string
  items?: Array<{
    title: string
    recognitions?: Array<string>
    cta?: Button
    _type: 'item'
    _key: string
  }>
  featuredTitle?: string
  featuredBadge?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
}

export type ProjectReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'project'
}

export type StudyMoreLikeThis = {
  _type: 'studyMoreLikeThis'
  heading?: StudyMoreLikeThisHeading
  items: Array<
    {
      _key: string
    } & ProjectReference
  >
}

export type StudyTechStack = {
  _type: 'studyTechStack'
  eyebrow?: string
  tools: Array<string>
}

export type StudyTestimonial = {
  _type: 'studyTestimonial'
  eyebrow?: string
  quote?: StudyTestimonialQuote
}

export type StudyNumbers = {
  _type: 'studyNumbers'
  eyebrow?: string
  heading?: string
  footnote?: string
  stats: Array<{
    value: string
    label: string
    description?: string
    _key: string
  }>
}

export type StudyWhatWeBuilt = {
  _type: 'studyWhatWeBuilt'
  eyebrow?: string
  heading?: string
  features: Array<{
    number: string
    title: string
    body: string
    image?: ObjectImage
    _key: string
  }>
}

export type StudyKeyWins = {
  _type: 'studyKeyWins'
  eyebrow?: string
  heading?: string
  comparison?: Comparison
}

export type StudyApproach = {
  _type: 'studyApproach'
  eyebrow?: string
  heading?: StudyApproachHeading
  body?: string
  callout?: Callout
}

export type StudyChallenge = {
  _type: 'studyChallenge'
  eyebrow?: string
  heading: string
  body?: string
  issues?: Array<{
    tag: string
    body: string
    _key: string
  }>
}

export type StudyHero = {
  _type: 'studyHero'
  eyebrow?: string
  heading: string
  subheading?: string
  chapters?: Array<string>
  details?: Array<{
    label: string
    value: string
    _key: string
  }>
  heroImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
}

export type StudyHeroImage = {
  _type: 'studyHeroImage'
  image: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  alt?: string
}

export type InsightBlock = {
  _type: 'insightBlock'
  title: string
  text?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  sectionType?: 'none' | 'quote' | 'table' | 'card'
  quote?: Quote
  table?: Table
  card?: Card
}

export type PostReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'post'
}

export type InsightsGrid = {
  _type: 'insightsGrid'
  items: Array<
    {
      _key: string
    } & PostReference
  >
  categoryFilters?: Array<{
    label: string
    value: string
    _type: 'filter'
    _key: string
  }>
}

export type PortfolioMetrics = {
  _type: 'portfolioMetrics'
  items: Array<{
    value: string
    label: string
    _key: string
  }>
}

export type PortfolioCta = {
  _type: 'portfolioCta'
  heading?: PortfolioCtaHeading
  body: string
  cta?: Button
}

export type PortfolioGrid = {
  _type: 'portfolioGrid'
  items: Array<
    {
      _key: string
    } & ProjectReference
  >
}

export type PortfolioFeatured = {
  _type: 'portfolioFeatured'
  caseStudy: ProjectReference
}

export type WhyRomania = {
  _type: 'whyRomania'
  eyebrow?: string
  title: BlockContentTextOnly
  body: BlockContentTextOnly
  highlights?: Array<{
    stat: string
    description: string
    _type: 'highlight'
    _key: string
  }>
}

export type Compare = {
  _type: 'compare'
  eyebrow?: string
  heading: CompareHeading
  rows: Array<{
    label: string
    _key: string
  }>
  columns: Array<{
    name: string
    highlightColumn?: boolean
    values: Array<{
      available?: boolean
      _key: string
    }>
    _key: string
  }>
  closing: Closing
}

export type Reality = {
  _type: 'reality'
  eyebrow?: string
  heading?: RealityHeading
  body?: string
  points?: Array<{
    title: string
    body?: string
    _key: string
  }>
  cta?: Button
}

export type Industries = {
  _type: 'industries'
  eyebrow?: string
  heading?: string
  industries?: Array<{
    industry?: string
    description?: string
    _key: string
  }>
  metrics?: Array<{
    label?: string
    value?: string
    prefix?: string
    _key: string
  }>
}

export type ServiceReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'service'
}

export type AiServices = {
  _type: 'aiServices'
  eyebrow: string
  services: Array<{
    service: ServiceReference
    cta: Button
    _type: 'aiServiceCard'
    _key: string
  }>
}

export type ServiceHero = {
  _type: 'serviceHero'
  breadcrumb?: Breadcrumb
  eyebrow?: string
  headlineLines?: Array<string>
  description?: string
  cta?: Button
  leadingHighlights?: Array<{
    value: string
    label: string
    _key: string
  }>
  trailingHighlights?: Array<{
    value: string
    label: string
    _key: string
  }>
}

export type EngineeringServices = {
  _type: 'engineeringServices'
  eyebrow?: string
  services?: Array<{
    service?: ServiceReference
    ctaLabel?: string
    ctaHref?: string
    _key: string
  }>
}

export type Faq = {
  _type: 'faq'
  eyebrow?: string
  heading?: string
  items: Array<{
    question: string
    answer: Array<{
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        href?: string
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }>
    _key: string
  }>
}

export type Why = {
  _type: 'why'
  eyebrow?: string
  heading?: string
  points?: Array<{
    title?: string
    body?: string
    _key: string
  }>
}

export type WhatWeDo = {
  _type: 'whatWeDo'
  eyebrow?: string
  heading?: string
  ctaSection?: CtaSection
  cards: Array<{
    kind?: 'engineering' | 'ai'
    label?: string
    labelImage?: LabelImage
    labelImageLight?: LabelImageLight
    labelImageDark?: LabelImageDark
    title: string
    body?: string
    services?: Array<
      {
        _key: string
      } & ServiceReference
    >
    cta: Button
    texture?: boolean
    _key: string
  }>
}

export type TestimonialReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'testimonial'
}

export type Testimonials = {
  _type: 'testimonials'
  eyebrow: string
  logos: Array<{
    name: string
    logoLight: LogoLight
    logoDark?: LogoDark
    _key: string
  }>
  testimonials: Array<
    {
      _key: string
    } & TestimonialReference
  >
}

export type TeamMemberReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'teamMember'
}

export type Team = {
  _type: 'team'
  eyebrow?: string
  heading: string
  members: Array<
    {
      _key: string
    } & TeamMemberReference
  >
  closingStatement: string
}

export type Story = {
  _type: 'story'
  eyebrow?: string
  heading?: string
  milestones?: Array<{
    year?: string
    body?: string
    _key: string
  }>
}

export type Signature2 = {
  _type: 'signature2'
  eyebrow?: string
  headingFaded?: string
  headingBold?: string
  body?: string
  steps?: Array<{
    title?: string
    highlighted?: boolean
    graphic?: StepGraphic
    _type: 'step'
    _key: string
  }>
  cta?: Button
}

export type Signature = {
  _type: 'signature'
  eyebrow?: string
  heading?: BlockContentTextOnly
  body?: string
  secondaryLine?: string
  steps?: Array<{
    title?: string
    duration?: string
    body?: string
    _key: string
  }>
  cta?: Button
  valueCard?: ValueCard
}

export type Pricing = {
  _type: 'pricing'
  eyebrow?: string
  headingPrimary: string
  headingSecondary?: string
  tiers: Array<{
    width: 'half' | 'full'
    priceLayout: 'stacked' | 'split' | 'inline'
    badge?: string
    title: string
    price: string
    meta?: string
    description?: string
    ctaStyle: 'textLink' | 'button'
    cta?: Button
    _type: 'tier'
    _key: string
  }>
}

export type Portfolio = {
  _type: 'portfolio'
  eyebrow: string
  heading: string
  cards: Array<{
    project: ProjectReference
    _key: string
  }>
  cta?: Button
}

export type Origin = {
  _type: 'origin'
  eyebrow?: string
  heading: string
  body: string
  subtext?: string
}

export type Methodology = {
  _type: 'methodology'
  eyebrow?: string
  heading?: string
  steps?: Array<{
    title?: string
    body?: string
    _key: string
  }>
}

export type Cta = {
  _type: 'cta'
  heading: string
  body: string
  cta: Button
  subtext?: string
}

export type HomeHero = {
  _type: 'homeHero'
  label?: string
  heading?: string
  body?: string
  primaryCta?: Button
  stats?: string
  dimensionLine?: string
  ctaText: BlockContentTextOnly
  secondaryCta?: Button
}

export type Booking = {
  _type: 'booking'
  eyebrow?: string
  heading?: Heading
  callTitle: string
  teamMember: TeamMemberReference
  whatToExpectHeading?: string
  expectations: Array<string>
  schedulerUrl?: string
}

export type CookieSettings = {
  _type: 'cookieSettings'
  enabled?: boolean
  bannerTitle: string
  bannerDescription?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: Array<
      {
        _key: string
      } & Link
    >
    level?: number
    _type: 'block'
    _key: string
  }>
  preferencesTitle: string
  preferencesDescription: string
  acceptAllLabel: string
  initialSaveLabel: string
  customizeLabel: string
  rejectAllLabel: string
  savePreferencesLabel: string
  backLabel: string
  footerButtonLabel: string
  categories?: Array<{
    title: string
    description: string
    required?: boolean
    defaultEnabled?: boolean
    lockedLabel?: string
    _key: string
  }>
}

export type ContactHero = {
  _type: 'contactHero'
  eyebrow?: string
  heading: string
  description: string
  stats?: Array<{
    number: number
    suffix?: string
    label: string
    _key: string
  }>
  steps: Array<{
    title: string
    description: string
    _key: string
  }>
  formConfig?: FormConfig
}

export type PageHero = {
  _type: 'pageHero'
  eyebrow?: string
  heading?: BlockContentTextOnly
  subheading?: string
  stats?: Array<{
    number: number
    suffix?: string
    label: string
    _key: string
  }>
  featured?: ProjectReference | PostReference
}

export type List = {
  _type: 'list'
  pageBuilder?: null
}

export type PageReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'page'
}

export type Link = {
  _type: 'link'
  linkType?: 'href' | 'page' | 'post' | 'service' | 'project'
  href?: string
  page?: PageReference
  post?: PostReference
  service?: ServiceReference
  project?: ProjectReference
  openInNewTab?: boolean
}

export type Seo = {
  _type: 'seo'
  metaTitle?: string
  metaDescription?: string
  metaKeywords?: Array<string>
  seoTitleSuffix?: string
  canonicalUrl?: string
  robotsMode?: 'inherit' | 'indexFollow' | 'noIndexNoFollow' | 'custom'
  robots?: string
  googleBot?: string
  noIndex?: boolean
  noFollow?: boolean
  noArchive?: boolean
  noSnippet?: boolean
  noImageIndex?: boolean
  maxSnippet?: number
  maxImagePreview?: string
  maxVideoPreview?: number
  paginationPrevUrl?: string
  paginationNextUrl?: string
  ogTitle?: string
  ogDescription?: string
  ogImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  ogType?: 'website' | 'article' | 'profile'
  ogUrl?: string
  ogSiteName?: string
  ogLocale?: string
  twitterCard?: 'summary' | 'summary_large_image'
  twitterTitle?: string
  twitterDescription?: string
  twitterImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  twitterSite?: string
  twitterCreator?: string
  socialTitle?: string
  socialDescription?: string
  socialImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  socialImageAlt?: string
  schemaType?: 'WebPage' | 'AboutPage' | 'Service' | 'Article' | 'FAQPage' | 'ContactPage'
  structuredDataMode?: 'inherit' | 'generated' | 'custom'
  structuredData?: string
  enableBreadcrumbSchema?: boolean
  enableFaqSchema?: boolean
  searchTitle?: string
  searchDescription?: string
  breadcrumbTitle?: string
  locale?: string
  themeColor?: string
  applicationName?: string
  category?: string
  referrer?: string
  formatDetection?: string
}

export type BlockContentTextOnly = Array<{
  children?: Array<{
    marks?: Array<string>
    text?: string
    _type: 'span'
    _key: string
  }>
  style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
  listItem?: 'bullet' | 'number'
  markDefs?: Array<{
    href?: string
    _type: 'link'
    _key: string
  }>
  level?: number
  _type: 'block'
  _key: string
}>

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        linkType?: 'href' | 'page' | 'post'
        href?: string
        page?: PageReference
        post?: PostReference
        openInNewTab?: boolean
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }
  | {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
      _key: string
    }
>

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top: number
  bottom: number
  left: number
  right: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x: number
  y: number
  height: number
  width: number
}

export type Button = {
  _type: 'button'
  buttonText?: string
  link?: Link
}

export type ResourceRequest = {
  _id: string
  _type: 'resourceRequest'
  _createdAt: string
  _updatedAt: string
  _rev: string
  email?: string
  resourceRequested?: string
  receivedAt: string
}

export type ContactSubmission = {
  _id: string
  _type: 'contactSubmission'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  email: string
  company?: string
  phone?: string
  projectType?: string
  budget?: string
  hearAboutUs?: string
  message: string
  receivedAt: string
  status?: 'new' | 'reviewed' | 'responded' | 'archived'
  notes?: string
}

export type Testimonial = {
  _id: string
  _type: 'testimonial'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  attribution: string
  quote: string
  profilePicture?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  rating?: number
}

export type SeoSettings = {
  _id: string
  _type: 'seoSettings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  siteName: string
  defaultSeo?: Seo
  googleSiteVerification?: string
  bingSiteVerification?: string
  pinterestVerification?: string
  yandexVerification?: string
  facebookDomainVerification?: string
}

export type SiteSettings = {
  _id: string
  _type: 'siteSettings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  description?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: Array<{
      linkType?: 'href' | 'page' | 'post'
      href?: string
      page?: PageReference
      post?: PostReference
      openInNewTab?: boolean
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  ogImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    metadataBase?: string
    _type: 'image'
  }
  brandName: string
  logoPicture?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  legalName?: string
  email?: string
  phoneNumber?: string
  location?: string
  instagram?: string
  facebook?: string
  linkedin?: string
  github?: string
  x?: string
  tiktok?: string
  cta?: Button
  navLinks?: Array<{
    label: string
    page?: PageReference
    href?: string
    _key: string
  }>
  footerColumns?: Array<{
    title: string
    links?: Array<{
      label: string
      linkType: 'page' | 'service' | 'href'
      page?: PageReference
      service?: ServiceReference
      href?: string
      accent?: boolean
      _key: string
    }>
    _key: string
  }>
  legalLinks?: Array<
    {
      _key: string
    } & PageReference
  >
  cookieSettings?: CookieSettings
}

export type InsightCategoryReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'insightCategory'
}

export type Post = {
  _id: string
  _type: 'post'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
  publishedAt?: string
  excerpt?: string
  coverImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  author?: TeamMemberReference
  category?: InsightCategoryReference
  readTime?: number
  featured?: boolean
  relatedInsights?: Array<
    {
      _key: string
    } & PostReference
  >
  order?: number
  stats?: Array<{
    value?: string
    label?: string
    _type: 'stat'
    _key: string
  }>
  sources?: Array<{
    title: string
    url?: string
    author?: string
    publishedDate?: string
    _type: 'source'
    _key: string
  }>
  pageBuilder?: Array<
    | ({
        _key: string
      } & PageHero)
    | ({
        _key: string
      } & ContactHero)
    | ({
        _key: string
      } & Booking)
    | ({
        _key: string
      } & HomeHero)
    | ({
        _key: string
      } & Cta)
    | ({
        _key: string
      } & Methodology)
    | ({
        _key: string
      } & Origin)
    | ({
        _key: string
      } & Portfolio)
    | ({
        _key: string
      } & Pricing)
    | ({
        _key: string
      } & Signature)
    | ({
        _key: string
      } & Signature2)
    | ({
        _key: string
      } & Story)
    | ({
        _key: string
      } & Team)
    | ({
        _key: string
      } & Testimonials)
    | ({
        _key: string
      } & WhatWeDo)
    | ({
        _key: string
      } & Why)
    | ({
        _key: string
      } & EngineeringServices)
    | ({
        _key: string
      } & ServiceHero)
    | ({
        _key: string
      } & AiServices)
    | ({
        _key: string
      } & ServiceNavigator)
    | ({
        _key: string
      } & Industries)
    | ({
        _key: string
      } & Reality)
    | ({
        _key: string
      } & Compare)
    | ({
        _key: string
      } & Steps)
    | ({
        _key: string
      } & WhyRomania)
    | ({
        _key: string
      } & Faq)
    | ({
        _key: string
      } & InsightsGrid)
    | ({
        _key: string
      } & PortfolioFeatured)
    | ({
        _key: string
      } & PortfolioGrid)
    | ({
        _key: string
      } & PortfolioCta)
    | ({
        _key: string
      } & PortfolioMetrics)
    | ({
        _key: string
      } & Awards)
    | ({
        _key: string
      } & Place)
    | ({
        _key: string
      } & Press)
    | ({
        _key: string
      } & TechStack)
    | ({
        _key: string
      } & FreeResources)
    | ({
        _key: string
      } & InsightBlock)
    | ({
        _key: string
      } & SoundFamiliar)
    | ({
        _key: string
      } & IsThisForYou)
    | ({
        _key: string
      } & StudyHeroImage)
    | ({
        _key: string
      } & StudyHero)
    | ({
        _key: string
      } & StudyChallenge)
    | ({
        _key: string
      } & StudyApproach)
    | ({
        _key: string
      } & StudyKeyWins)
    | ({
        _key: string
      } & StudyWhatWeBuilt)
    | ({
        _key: string
      } & StudyNumbers)
    | ({
        _key: string
      } & StudyTestimonial)
    | ({
        _key: string
      } & StudyTechStack)
    | ({
        _key: string
      } & StudyMoreLikeThis)
    | ({
        _key: string
      } & StudyClosingCta)
  >
  seo?: Seo
}

export type InsightCategory = {
  _id: string
  _type: 'insightCategory'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
  description?: string
}

export type Slug = {
  _type: 'slug'
  current: string
  source?: string
}

export type TeamMember = {
  _id: string
  _type: 'teamMember'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  order: number
  role: string
  bio: string
  portrait?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
}

export type Page = {
  _id: string
  _type: 'page'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  slug: Slug
  pageType?: 'home' | 'services' | 'insights' | 'caseStudies'
  pageBuilder?: Array<
    | ({
        _key: string
      } & PageHero)
    | ({
        _key: string
      } & ContactHero)
    | ({
        _key: string
      } & Booking)
    | ({
        _key: string
      } & HomeHero)
    | ({
        _key: string
      } & Cta)
    | ({
        _key: string
      } & Methodology)
    | ({
        _key: string
      } & Origin)
    | ({
        _key: string
      } & Portfolio)
    | ({
        _key: string
      } & Pricing)
    | ({
        _key: string
      } & Signature)
    | ({
        _key: string
      } & Signature2)
    | ({
        _key: string
      } & Story)
    | ({
        _key: string
      } & Team)
    | ({
        _key: string
      } & Testimonials)
    | ({
        _key: string
      } & WhatWeDo)
    | ({
        _key: string
      } & Why)
    | ({
        _key: string
      } & EngineeringServices)
    | ({
        _key: string
      } & ServiceHero)
    | ({
        _key: string
      } & AiServices)
    | ({
        _key: string
      } & ServiceNavigator)
    | ({
        _key: string
      } & Industries)
    | ({
        _key: string
      } & Reality)
    | ({
        _key: string
      } & Compare)
    | ({
        _key: string
      } & Steps)
    | ({
        _key: string
      } & WhyRomania)
    | ({
        _key: string
      } & Faq)
    | ({
        _key: string
      } & InsightsGrid)
    | ({
        _key: string
      } & PortfolioFeatured)
    | ({
        _key: string
      } & PortfolioGrid)
    | ({
        _key: string
      } & PortfolioCta)
    | ({
        _key: string
      } & PortfolioMetrics)
    | ({
        _key: string
      } & Awards)
    | ({
        _key: string
      } & Place)
    | ({
        _key: string
      } & Press)
    | ({
        _key: string
      } & TechStack)
    | ({
        _key: string
      } & FreeResources)
    | ({
        _key: string
      } & InsightBlock)
    | ({
        _key: string
      } & SoundFamiliar)
    | ({
        _key: string
      } & IsThisForYou)
    | ({
        _key: string
      } & StudyHeroImage)
    | ({
        _key: string
      } & StudyHero)
    | ({
        _key: string
      } & StudyChallenge)
    | ({
        _key: string
      } & StudyApproach)
    | ({
        _key: string
      } & StudyKeyWins)
    | ({
        _key: string
      } & StudyWhatWeBuilt)
    | ({
        _key: string
      } & StudyNumbers)
    | ({
        _key: string
      } & StudyTestimonial)
    | ({
        _key: string
      } & StudyTechStack)
    | ({
        _key: string
      } & StudyMoreLikeThis)
    | ({
        _key: string
      } & StudyClosingCta)
  >
  seo?: Seo
}

export type IndustryReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'industry'
}

export type Project = {
  _id: string
  _type: 'project'
  _createdAt: string
  _updatedAt: string
  _rev: string
  client: string
  title: string
  year: string
  slug: Slug
  category: ServiceReference
  industry: IndustryReference
  tagline: string
  metric?: string
  metricLabel?: string
  thumb?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  pageBuilder?: Array<
    | ({
        _key: string
      } & PageHero)
    | ({
        _key: string
      } & ContactHero)
    | ({
        _key: string
      } & Booking)
    | ({
        _key: string
      } & HomeHero)
    | ({
        _key: string
      } & Cta)
    | ({
        _key: string
      } & Methodology)
    | ({
        _key: string
      } & Origin)
    | ({
        _key: string
      } & Portfolio)
    | ({
        _key: string
      } & Pricing)
    | ({
        _key: string
      } & Signature)
    | ({
        _key: string
      } & Signature2)
    | ({
        _key: string
      } & Story)
    | ({
        _key: string
      } & Team)
    | ({
        _key: string
      } & Testimonials)
    | ({
        _key: string
      } & WhatWeDo)
    | ({
        _key: string
      } & Why)
    | ({
        _key: string
      } & EngineeringServices)
    | ({
        _key: string
      } & ServiceHero)
    | ({
        _key: string
      } & AiServices)
    | ({
        _key: string
      } & ServiceNavigator)
    | ({
        _key: string
      } & Industries)
    | ({
        _key: string
      } & Reality)
    | ({
        _key: string
      } & Compare)
    | ({
        _key: string
      } & Steps)
    | ({
        _key: string
      } & WhyRomania)
    | ({
        _key: string
      } & Faq)
    | ({
        _key: string
      } & InsightsGrid)
    | ({
        _key: string
      } & PortfolioFeatured)
    | ({
        _key: string
      } & PortfolioGrid)
    | ({
        _key: string
      } & PortfolioCta)
    | ({
        _key: string
      } & PortfolioMetrics)
    | ({
        _key: string
      } & Awards)
    | ({
        _key: string
      } & Place)
    | ({
        _key: string
      } & Press)
    | ({
        _key: string
      } & TechStack)
    | ({
        _key: string
      } & FreeResources)
    | ({
        _key: string
      } & InsightBlock)
    | ({
        _key: string
      } & SoundFamiliar)
    | ({
        _key: string
      } & IsThisForYou)
    | ({
        _key: string
      } & StudyHeroImage)
    | ({
        _key: string
      } & StudyHero)
    | ({
        _key: string
      } & StudyChallenge)
    | ({
        _key: string
      } & StudyApproach)
    | ({
        _key: string
      } & StudyKeyWins)
    | ({
        _key: string
      } & StudyWhatWeBuilt)
    | ({
        _key: string
      } & StudyNumbers)
    | ({
        _key: string
      } & StudyTestimonial)
    | ({
        _key: string
      } & StudyTechStack)
    | ({
        _key: string
      } & StudyMoreLikeThis)
    | ({
        _key: string
      } & StudyClosingCta)
  >
  publishedAt?: string
  seo?: Seo
}

export type Industry = {
  _id: string
  _type: 'industry'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  slug: Slug
  order?: number
}

export type Service = {
  _id: string
  _type: 'service'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  description: string
  price: string
  category: 'engineering' | 'ai'
  tag: string
  slug: Slug
  duration: string
  pageBuilder?: Array<
    | ({
        _key: string
      } & PageHero)
    | ({
        _key: string
      } & ContactHero)
    | ({
        _key: string
      } & Booking)
    | ({
        _key: string
      } & HomeHero)
    | ({
        _key: string
      } & Cta)
    | ({
        _key: string
      } & Methodology)
    | ({
        _key: string
      } & Origin)
    | ({
        _key: string
      } & Portfolio)
    | ({
        _key: string
      } & Pricing)
    | ({
        _key: string
      } & Signature)
    | ({
        _key: string
      } & Signature2)
    | ({
        _key: string
      } & Story)
    | ({
        _key: string
      } & Team)
    | ({
        _key: string
      } & Testimonials)
    | ({
        _key: string
      } & WhatWeDo)
    | ({
        _key: string
      } & Why)
    | ({
        _key: string
      } & EngineeringServices)
    | ({
        _key: string
      } & ServiceHero)
    | ({
        _key: string
      } & AiServices)
    | ({
        _key: string
      } & ServiceNavigator)
    | ({
        _key: string
      } & Industries)
    | ({
        _key: string
      } & Reality)
    | ({
        _key: string
      } & Compare)
    | ({
        _key: string
      } & Steps)
    | ({
        _key: string
      } & WhyRomania)
    | ({
        _key: string
      } & Faq)
    | ({
        _key: string
      } & InsightsGrid)
    | ({
        _key: string
      } & PortfolioFeatured)
    | ({
        _key: string
      } & PortfolioGrid)
    | ({
        _key: string
      } & PortfolioCta)
    | ({
        _key: string
      } & PortfolioMetrics)
    | ({
        _key: string
      } & Awards)
    | ({
        _key: string
      } & Place)
    | ({
        _key: string
      } & Press)
    | ({
        _key: string
      } & TechStack)
    | ({
        _key: string
      } & FreeResources)
    | ({
        _key: string
      } & InsightBlock)
    | ({
        _key: string
      } & SoundFamiliar)
    | ({
        _key: string
      } & IsThisForYou)
    | ({
        _key: string
      } & StudyHeroImage)
    | ({
        _key: string
      } & StudyHero)
    | ({
        _key: string
      } & StudyChallenge)
    | ({
        _key: string
      } & StudyApproach)
    | ({
        _key: string
      } & StudyKeyWins)
    | ({
        _key: string
      } & StudyWhatWeBuilt)
    | ({
        _key: string
      } & StudyNumbers)
    | ({
        _key: string
      } & StudyTestimonial)
    | ({
        _key: string
      } & StudyTechStack)
    | ({
        _key: string
      } & StudyMoreLikeThis)
    | ({
        _key: string
      } & StudyClosingCta)
  >
  seo?: Seo
}

export type SanityAssistInstructionTask = {
  _type: 'sanity.assist.instructionTask'
  path?: string
  instructionKey?: string
  started?: string
  updated?: string
  info?: string
}

export type SanityAssistTaskStatus = {
  _type: 'sanity.assist.task.status'
  tasks?: Array<
    {
      _key: string
    } & SanityAssistInstructionTask
  >
}

export type SanityAssistSchemaTypeAnnotations = {
  _type: 'sanity.assist.schemaType.annotations'
  title?: string
  fields?: Array<
    {
      _key: string
    } & SanityAssistSchemaTypeField
  >
}

export type SanityAssistOutputType = {
  _type: 'sanity.assist.output.type'
  type?: string
}

export type SanityAssistOutputField = {
  _type: 'sanity.assist.output.field'
  path?: string
}

export type AssistInstructionContextReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'assist.instruction.context'
}

export type SanityAssistInstructionContext = {
  _type: 'sanity.assist.instruction.context'
  reference: AssistInstructionContextReference
}

export type AssistInstructionContext = {
  _id: string
  _type: 'assist.instruction.context'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  context?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: null
    level?: number
    _type: 'block'
    _key: string
  }>
}

export type SanityAssistInstructionUserInput = {
  _type: 'sanity.assist.instruction.userInput'
  message: string
  description?: string
}

export type SanityAssistInstructionPrompt = Array<{
  children?: Array<
    | {
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }
    | ({
        _key: string
      } & SanityAssistInstructionFieldRef)
    | ({
        _key: string
      } & SanityAssistInstructionContext)
    | ({
        _key: string
      } & SanityAssistInstructionUserInput)
  >
  style?: 'normal'
  listItem?: never
  markDefs?: null
  level?: number
  _type: 'block'
  _key: string
}>

export type SanityAssistInstructionFieldRef = {
  _type: 'sanity.assist.instruction.fieldRef'
  path?: string
}

export type SanityAssistInstruction = {
  _type: 'sanity.assist.instruction'
  prompt?: SanityAssistInstructionPrompt
  icon?: string
  title?: string
  userId?: string
  createdById?: string
  output?: Array<
    | ({
        _key: string
      } & SanityAssistOutputField)
    | ({
        _key: string
      } & SanityAssistOutputType)
  >
}

export type SanityAssistSchemaTypeField = {
  _type: 'sanity.assist.schemaType.field'
  path?: string
  instructions?: Array<
    {
      _key: string
    } & SanityAssistInstruction
  >
}

export type MediaTag = {
  _id: string
  _type: 'media.tag'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: Slug
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height: number
  width: number
  aspectRatio: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | FormConfig
  | Heading
  | ValueCard
  | CtaSection
  | Breadcrumb
  | RealityHeading
  | CompareHeading
  | Closing
  | PortfolioCtaHeading
  | FreeResourcesHeading
  | Quote
  | Table
  | Card
  | StudyApproachHeading
  | Callout
  | Comparison
  | StudyTestimonialQuote
  | StudyMoreLikeThisHeading
  | StudyClosingCtaHeading
  | SanityImageAssetReference
  | Graphic
  | StepGraphic
  | LogoLight
  | LogoDark
  | LabelImage
  | LabelImageLight
  | LabelImageDark
  | Logo
  | SanityFileAssetReference
  | ResourceFile
  | ObjectImage
  | Steps
  | ServiceNavigator
  | SoundFamiliar
  | IsThisForYou
  | FreeResources
  | StudyClosingCta
  | TechStack
  | Press
  | Place
  | Awards
  | ProjectReference
  | StudyMoreLikeThis
  | StudyTechStack
  | StudyTestimonial
  | StudyNumbers
  | StudyWhatWeBuilt
  | StudyKeyWins
  | StudyApproach
  | StudyChallenge
  | StudyHero
  | StudyHeroImage
  | InsightBlock
  | PostReference
  | InsightsGrid
  | PortfolioMetrics
  | PortfolioCta
  | PortfolioGrid
  | PortfolioFeatured
  | WhyRomania
  | Compare
  | Reality
  | Industries
  | ServiceReference
  | AiServices
  | ServiceHero
  | EngineeringServices
  | Faq
  | Why
  | WhatWeDo
  | TestimonialReference
  | Testimonials
  | TeamMemberReference
  | Team
  | Story
  | Signature2
  | Signature
  | Pricing
  | Portfolio
  | Origin
  | Methodology
  | Cta
  | HomeHero
  | Booking
  | CookieSettings
  | ContactHero
  | PageHero
  | List
  | PageReference
  | Link
  | Seo
  | BlockContentTextOnly
  | BlockContent
  | SanityImageCrop
  | SanityImageHotspot
  | Button
  | ResourceRequest
  | ContactSubmission
  | Testimonial
  | SeoSettings
  | SiteSettings
  | InsightCategoryReference
  | Post
  | InsightCategory
  | Slug
  | TeamMember
  | Page
  | IndustryReference
  | Project
  | Industry
  | Service
  | SanityAssistInstructionTask
  | SanityAssistTaskStatus
  | SanityAssistSchemaTypeAnnotations
  | SanityAssistOutputType
  | SanityAssistOutputField
  | AssistInstructionContextReference
  | SanityAssistInstructionContext
  | AssistInstructionContext
  | SanityAssistInstructionUserInput
  | SanityAssistInstructionPrompt
  | SanityAssistInstructionFieldRef
  | SanityAssistInstruction
  | SanityAssistSchemaTypeField
  | MediaTag
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
