const surfaceStyle = {
  backgroundColor: "#111111",
  border: "1px solid #2b2b2b",
  borderRadius: "28px",
} as const;

const labelStyle = {
  color: "#9ca3af",
  fontFamily: '"IBM Plex Mono", "SFMono-Regular", Consolas, "Liberation Mono", Menlo, monospace',
  fontSize: "12px",
  letterSpacing: "0.08em",
  textTransform: "uppercase" as const,
};

const valueStyle = {
  color: "#f5f5f5",
  fontFamily: 'Inter, "Segoe UI", Helvetica, Arial, sans-serif',
  fontSize: "15px",
  fontWeight: 500,
  lineHeight: "22px",
};

function formatEmpty(value?: string) {
  return value && value.trim().length > 0 ? value : "Not provided";
}

export function ContactNotification({
  name,
  email,
  company,
  phone,
  projectType,
  budget,
  message,
  source,
  receivedAt,
  forClient = false,
}: {
  name: string;
  email: string;
  company?: string;
  phone?: string;
  projectType?: string;
  budget?: string;
  message: string;
  source?: string;
  receivedAt: string;
  forClient?: boolean;
}) {
  const rows: Array<[string, string]> = [
    ["Name", name],
    ["Email", email],
    ["Company", formatEmpty(company)],
    ["Phone", formatEmpty(phone)],
    ["Project type", formatEmpty(projectType)],
    ["Budget", formatEmpty(budget)],
    ["Source", formatEmpty(source || "/contact")],
    ["Received", receivedAt],
  ];

  const heading = forClient
    ? "Your message is in"
    : "New contact form submission";
  const intro = forClient
    ? "Thanks for reaching out to 1210. We have your message and will come back with the right next step as soon as possible."
    : "A new lead came in through the website contact form. Details are below.";
  const footer = forClient
    ? "If you want to add anything else, just reply to this email and we will keep everything in one thread."
    : "This email was generated by the contact form on neovision.dev. Reply directly to continue the conversation.";

  return (
    <div
      style={{
        margin: 0,
        padding: "32px 18px",
        backgroundColor: "#050505",
        color: "#f5f5f5",
        fontFamily: 'Inter, "Segoe UI", Helvetica, Arial, sans-serif',
      }}
    >
      <div style={{ maxWidth: "680px", margin: "0 auto" }}>
        <div
          style={{
            ...surfaceStyle,
            overflow: "hidden",
            boxShadow: "0 32px 80px rgba(0, 0, 0, 0.32)",
          }}
        >
          <div
            style={{
              padding: "12px 24px",
              background:
                "linear-gradient(90deg, #ff5500 0%, #ff7a1a 52%, #f5d94f 100%)",
            }}
          >
            <p
              style={{
                margin: 0,
                color: "#111111",
                fontSize: "12px",
                fontWeight: 700,
                letterSpacing: "0.12em",
                textTransform: "uppercase",
              }}
            >
              1210
            </p>
          </div>

          <div style={{ padding: "32px 24px 28px" }}>
            <div
              style={{
                display: "inline-block",
                marginBottom: "18px",
                padding: "7px 12px",
                borderRadius: "999px",
                backgroundColor: "rgba(255, 85, 0, 0.14)",
                border: "1px solid rgba(255, 85, 0, 0.32)",
                color: "#ff8a4c",
                fontSize: "12px",
                fontWeight: 700,
                letterSpacing: "0.08em",
                textTransform: "uppercase",
              }}
            >
              {forClient ? "Contact confirmation" : "Contact pipeline"}
            </div>

            <h1
              style={{
                margin: "0 0 14px",
                color: "#ffffff",
                fontSize: "34px",
                lineHeight: "38px",
                fontWeight: 700,
                letterSpacing: "-0.03em",
              }}
            >
              {heading}
            </h1>

            <p
              style={{
                margin: "0 0 28px",
                color: "#d1d5db",
                fontSize: "16px",
                lineHeight: "26px",
                maxWidth: "560px",
              }}
            >
              {intro}
            </p>

            <div
              style={{
                marginBottom: "24px",
                padding: "22px",
                borderRadius: "20px",
                backgroundColor: "#171717",
                border: "1px solid #2b2b2b",
              }}
            >
              <table
                cellPadding={0}
                cellSpacing={0}
                style={{
                  width: "100%",
                  borderCollapse: "collapse",
                }}
              >
                <tbody>
                  {rows.map(([label, value], index) => (
                    <tr key={label}>
                      <td
                        style={{
                          ...labelStyle,
                          width: "152px",
                          padding: "0 18px 16px 0",
                          verticalAlign: "top",
                          borderBottom:
                            index === rows.length - 1
                              ? "none"
                              : "1px solid #262626",
                        }}
                      >
                        {label}
                      </td>
                      <td
                        style={{
                          ...valueStyle,
                          padding: "0 0 16px",
                          verticalAlign: "top",
                          borderBottom:
                            index === rows.length - 1
                              ? "none"
                              : "1px solid #262626",
                        }}
                      >
                        {value}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>

            <div
              style={{
                padding: "22px",
                borderRadius: "20px",
                backgroundColor: "#0b0b0b",
                border: "1px solid #262626",
              }}
            >
              <p style={{ ...labelStyle, margin: "0 0 10px", color: "#ff8a4c" }}>
                Message
              </p>
              <p
                style={{
                  margin: 0,
                  color: "#f3f4f6",
                  fontSize: "15px",
                  lineHeight: "25px",
                  whiteSpace: "pre-wrap",
                }}
              >
                {message}
              </p>
            </div>

            <div
              style={{
                marginTop: "28px",
                paddingTop: "20px",
                borderTop: "1px solid #262626",
              }}
            >
              <p
                style={{
                  margin: 0,
                  color: "#9ca3af",
                  fontSize: "13px",
                  lineHeight: "22px",
                }}
              >
                {footer}
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
