const surfaceStyle = {
  backgroundColor: "#111111",
  border: "1px solid #2b2b2b",
  borderRadius: "28px",
} as const;

const labelStyle = {
  color: "#9ca3af",
  fontFamily: '"IBM Plex Mono", "SFMono-Regular", Consolas, "Liberation Mono", Menlo, monospace',
  fontSize: "12px",
  letterSpacing: "0.08em",
  textTransform: "uppercase" as const,
};

const valueStyle = {
  color: "#f5f5f5",
  fontFamily: 'Inter, "Segoe UI", Helvetica, Arial, sans-serif',
  fontSize: "15px",
  fontWeight: 500,
  lineHeight: "22px",
};

function formatEmpty(value?: string) {
  return value && value.trim().length > 0 ? value : "Not provided";
}

function formatDate(isoString: string): string {
  const date = new Date(isoString);
  return date.toLocaleString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
    timeZoneName: 'short',
  });
}

export function ResourceRequestNotification({
  email,
  resourceRequested,
  receivedAt,
  asFile,
  url,
  forClient = false,
}: {
  email: string;
  resourceRequested: string;
  receivedAt: string;
  asFile?: boolean;
  url?: string;
  forClient?: boolean;
}) {
  const rows: Array<[string, string | React.ReactNode]> = [
    ["Email", email],
    ["Resource requested", resourceRequested],
    ["Received", formatDate(receivedAt)],
    // Only show URL row if it's not a file
    ...(!asFile && url ? [["URL", <a key="url" href={url} style={{ color: "#ff8a4c", textDecoration: "underline" }}>{url}</a>]] as [string, React.ReactNode][] : []),
  ];

  const heading = forClient
    ? "Your resource is on its way"
    : "New resource request";
  const intro = forClient
    ? "Thanks for requesting a resource from Neo Vision. We've received your details and the resource will be sent to your inbox shortly."
    : "A user has requested a free resource from the website. Details are below.";
  const footer = forClient
    ? "Need help or have questions? Just reply to this email and we'll get back to you."
    : "This email was generated by the resource request form on neovision.dev. Reply directly to follow up with the requester.";

  return (
    <div
      style={{
        margin: 0,
        padding: "32px 18px",
        backgroundColor: "#050505",
        color: "#f5f5f5",
        fontFamily: 'Inter, "Segoe UI", Helvetica, Arial, sans-serif',
      }}
    >
      <div style={{ maxWidth: "680px", margin: "0 auto" }}>
        <div
          style={{
            ...surfaceStyle,
            overflow: "hidden",
            boxShadow: "0 32px 80px rgba(0, 0, 0, 0.32)",
          }}
        >
          <div
            style={{
              padding: "12px 24px",
              background:
                "linear-gradient(90deg, #ff5500 0%, #ff7a1a 52%, #f5d94f 100%)",
            }}
          >
            <div style={{ display: 'flex', alignItems: 'center' }}>
              <svg xmlns="http://www.w3.org/2000/svg" width="46" height="28" viewBox="0 0 46 28" fill="none">
                <path d="M0 4.15624C0 3.88434 0.11653 3.61244 0.310747 3.37938L3.34053 0.388434C3.57359 0.155374 3.92318 0 4.27277 0C4.62237 0 4.97196 0.155374 5.20502 0.388434L17.0134 12.158L14.5663 14.5663L3.53475 3.53475V27.1904H0V4.15624ZM18.2952 27.1904V0H21.83V27.1904H18.2952Z" fill="#111111"/>
                <path d="M28.6998 27.5788C28.3114 27.5788 28.0006 27.4234 27.7287 27.1904L24.7378 24.1994C24.5436 23.9664 24.427 23.6945 24.427 23.4226V0.388434H27.9618V24.0052L41.7512 10.177V0.388434H45.2859V9.4001C45.2859 10.7596 44.781 12.0415 43.8099 12.9737L29.6321 27.1904C29.3601 27.4234 29.0494 27.5788 28.6998 27.5788Z" fill="#111111"/>
              </svg>
            </div>
          </div>

          <div style={{ padding: "32px 24px 28px" }}>
            <div
              style={{
                display: "inline-block",
                marginBottom: "18px",
                padding: "7px 12px",
                borderRadius: "999px",
                backgroundColor: "rgba(255, 85, 0, 0.14)",
                border: "1px solid rgba(255, 85, 0, 0.32)",
                color: "#ff8a4c",
                fontSize: "12px",
                fontWeight: 700,
                letterSpacing: "0.08em",
                textTransform: "uppercase",
              }}
            >
              {forClient ? "Resource request confirmation" : "Resource request pipeline"}
            </div>

            <h1
              style={{
                margin: "0 0 14px",
                color: "#ffffff",
                fontSize: "34px",
                lineHeight: "38px",
                fontWeight: 700,
                letterSpacing: "-0.03em",
              }}
            >
              {heading}
            </h1>

            <p
              style={{
                margin: "0 0 28px",
                color: "#d1d5db",
                fontSize: "16px",
                lineHeight: "26px",
                maxWidth: "560px",
              }}
            >
              {intro}
            </p>

            <div
              style={{
                marginBottom: "24px",
                padding: "22px",
                borderRadius: "20px",
                backgroundColor: "#171717",
                border: "1px solid #2b2b2b",
              }}
            >
              <table
                cellPadding={0}
                cellSpacing={0}
                style={{
                  width: "100%",
                  borderCollapse: "collapse",
                }}
              >
                <tbody>
                  {rows.map(([label, value], index) => (
                    <tr key={label}>
                      <td
                        style={{
                          ...labelStyle,
                          width: "152px",
                          padding: "12px 18px 12px 0",
                          verticalAlign: "middle",
                          borderBottom:
                            index === rows.length - 1
                              ? "none"
                              : "1px solid #262626",
                        }}
                      >
                        {label}
                      </td>
                      <td
                        style={{
                          ...valueStyle,
                          padding: "12px 0",
                          verticalAlign: "middle",
                          borderBottom:
                            index === rows.length - 1
                              ? "none"
                              : "1px solid #262626",
                        }}
                      >
                        {value}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>

            <div
              style={{
                marginTop: "28px",
                paddingTop: "20px",
                borderTop: "1px solid #262626",
              }}
            >
              <p
                style={{
                  margin: 0,
                  color: "#9ca3af",
                  fontSize: "13px",
                  lineHeight: "22px",
                }}
              >
                {footer}
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
